sonar.projectKey=fhpeto_verademo-java
sonar.organization=fhpeto
sonar.sources=src/main/java/com/veracode/verademo,src/main/webapp,src/main/resources
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml